export const relationships = [
  // {
  //   key: '父亲',
  //   title: '父亲',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '母亲',
  //   title: '母亲',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '爷爷',
  //   title: '爷爷',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '奶奶',
  //   title: '奶奶',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '外公',
  //   title: '外公',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '外婆',
  //   title: '外婆',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  {
    key: '女儿',
    title: '女儿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '女婿',
    title: '女婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '儿子',
    title: '儿子',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '儿媳',
    title: '儿媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙子',
    title: '孙子',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙媳',
    title: '孙媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙女',
    title: '孙女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙婿',
    title: '孙婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '外孙子',
    title: '外孙子',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '外孙媳',
    title: '外孙媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
  },
  {
    key: '外孙女',
    title: '外孙女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '外孙婿',
    title: '外孙婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄男',
    title: '侄男',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄男媳',
    title: '侄男媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄女',
    title: '侄女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄男媳',
    title: '侄男媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂弟',
    title: '堂弟',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂弟媳',
    title: '堂弟媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂妹',
    title: '堂妹',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂妹婿',
    title: '堂妹婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表弟',
    title: '表弟',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '弟媳',
    title: '弟媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表妹',
    title: '表妹',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '妹婿',
    title: '妹婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表姐',
    title: '表姐',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表姐夫',
    title: '表姐夫',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表哥',
    title: '表哥',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '妹嫂',
    title: '妹嫂',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '哥哥',
    title: '哥哥',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '哥哥',
    title: '哥哥',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '嫂子',
    title: '嫂子',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '姐姐',
    title: '姐姐',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '姐夫',
    title: '姐夫',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '妹妹',
    title: '妹妹',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '妹婿',
    title: '妹婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '叔叔',
    title: '叔叔',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '舅舅',
    title: '舅舅',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '嬢嬢',
    title: '嬢嬢',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '同事',
    title: '同事',
    mainPassage: '携亲友',
    maleDecedentTitle: '同志',
    femaleDecedentTitle: '同志',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '亲友',
    title: '亲友',
    mainPassage: '携亲友',
    maleDecedentTitle: '同志',
    femaleDecedentTitle: '同志',
    firstCoupletEnding: '敬挽',
  },
];

export default {
  relationships,
};
