export const relationships = [
  // {
  //   key: '父亲',
  //   title: '父亲',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '母亲',
  //   title: '母亲',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '爷爷',
  //   title: '爷爷',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '奶奶',
  //   title: '奶奶',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '外公',
  //   title: '外公',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  // {
  //   key: '外婆',
  //   title: '外婆',
  //   mainPassage: '携全家',
  //   decedentTitle: '泣挽',
  // },
  {
    key: '女儿',
    title: '孝女',
    firstCoupletStarting: '孝',
    secondTitle: '女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '女婿',
    title: '孝婿',
    firstCoupletStarting: '孝',
    secondTitle: '婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '儿子',
    title: '孝男',
    firstCoupletStarting: '孝',
    secondTitle: '男',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '儿媳',
    title: '孝媳',
    firstCoupletStarting: '孝',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙子',
    title: '孙子',
    firstCoupletStarting: '孙',
    secondTitle: '男',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙媳',
    title: '孙媳',
    firstCoupletStarting: '孙',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙女',
    title: '孙女',
    firstCoupletStarting: '孙',
    secondTitle: '女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '孙婿',
    title: '孙婿',
    firstCoupletStarting: '孙',
    secondTitle: '婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '外孙子',
    title: '外孙子',
    firstCoupletStarting: '外孙',
    secondTitle: '男',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '外孙媳',
    title: '外孙媳',
    firstCoupletStarting: '外孙',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
  },
  {
    key: '外孙女',
    title: '外孙女',
    firstCoupletStarting: '外孙',
    secondTitle: '女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '外孙婿',
    title: '外孙婿',
    firstCoupletStarting: '外孙',
    secondTitle: '婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄男',
    title: '侄男',
    firstCoupletStarting: '侄男',
    secondTitle: '男',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄男媳',
    title: '侄男媳',
    firstCoupletStarting: '侄男',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄女',
    title: '侄女',
    firstCoupletStarting: '侄女',
    secondTitle: '女',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '侄女媳',
    title: '侄女媳',
    firstCoupletStarting: '侄女',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂弟',
    title: '堂弟',
    firstCoupletStarting: '堂弟',
    secondTitle: '弟',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂弟媳',
    title: '堂弟媳',
    firstCoupletStarting: '堂弟',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂妹',
    title: '堂妹',
    firstCoupletStarting: '堂妹',
    secondTitle: '妹',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '堂妹婿',
    title: '堂妹婿',
    firstCoupletStarting: '堂妹',
    secondTitle: '婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表弟',
    title: '表弟',
    firstCoupletStarting: '表弟',
    secondTitle: '弟',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表弟媳',
    title: '表弟媳',
    firstCoupletStarting: '表弟',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表妹',
    title: '表妹',
    firstCoupletStarting: '表妹',
    secondTitle: '妹',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表妹婿',
    title: '表妹婿',
    firstCoupletStarting: '表妹',
    secondTitle: '婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表姐',
    title: '表姐',
    firstCoupletStarting: '表姐',
    secondTitle: '姐',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表姐夫',
    title: '表姐夫',
    firstCoupletStarting: '表姐',
    secondTitle: '夫',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '表哥',
    title: '表哥',
    firstCoupletStarting: '表',
    secondTitle: '哥',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '妹嫂',
    title: '妹嫂',
    firstCoupletStarting: '表',
    secondTitle: '嫂',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '哥哥',
    title: '哥哥',
    firstCoupletStarting: '哥',
    secondTitle: '哥',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },

  {
    key: '嫂子',
    title: '嫂子',
    firstCoupletStarting: '哥',
    secondTitle: '嫂',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '弟弟',
    title: '弟弟',
    firstCoupletStarting: '弟',
    secondTitle: '弟',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '弟媳',
    title: '弟媳',
    firstCoupletStarting: '弟',
    secondTitle: '媳',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '姐姐',
    title: '姐姐',
    firstCoupletStarting: '姐',
    secondTitle: '姐',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '姐夫',
    title: '姐夫',
    firstCoupletStarting: '姐',
    secondTitle: '夫',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '妹妹',
    title: '妹妹',
    firstCoupletStarting: '妹',
    secondTitle: '妹',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '妹婿',
    title: '妹婿',
    firstCoupletStarting: '妹',
    secondTitle: '婿',
    mainPassage: '携全家',
    maleDecedentTitle: '大人',
    femaleDecedentTitle: '儒人',
    firstCoupletEnding: '泣挽',
  },
  {
    key: '同事',
    title: '同事',
    mainPassage: '携亲友',
    maleDecedentTitle: '同志',
    femaleDecedentTitle: '同志',
    firstCoupletEnding: '敬挽',
  },
  {
    key: '亲友',
    title: '亲友',
    mainPassage: '携亲友',
    maleDecedentTitle: '同志',
    femaleDecedentTitle: '同志',
    firstCoupletEnding: '敬挽',
  },
];

export default {
  relationships,
};
